language: php

php:
  - 5.4
  - 5.5
  - hhvm

notifications:
  email: false
  slack:
    secure: kpHmE/eLC+hky7FaCRK9bDVwbB3ohK+kyOAFjyKP4WJs/qV3ybEME7g0ZVGZAHmtOaqwGnXGFzCtJtDbAON54mBrF2qZYm+AhFd+ZFPAvdUyP2JitIh306AC32NVXQZKJyyUNi5dh77XQWE9/HNA2Nr0TOpdQxuoJUwPFhyYzoc=

before_install:
  - composer selfupdate

install:
  - composer install

before_script:
  - mkdir -p build/logs
  - mysql -e 'create database `harp-orm/transfer`;'
  - mysql harp-orm/transfer < tests/mysql.sql

script:
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - test -e build/logs/clover.xml && wget https://scrutinizer-ci.com/ocular.phar
  - test -e build/logs/clover.xml && php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
